#!/usr/bin/env bash
# =============================================================================
# SSH VPN Panel - Stunnel SSL/TLS Tunnel Management Module
# =============================================================================
# Handles Stunnel configuration, certificate management, service control,
# traffic monitoring, and auto-restart functionality.
# =============================================================================

[[ "${BASH_SOURCE[0]}" == "${0}" ]] && {
    echo "This module should be sourced, not executed directly."
    exit 1
}

# =============================================================================
# STUNNEL TUNNEL DATABASE
# =============================================================================
# Tunnel configs stored in ${STUNNEL_DIR}/tunnels/<name>.conf

STUNNEL_TUNNELS_DIR="${STUNNEL_DIR:-/etc/sshvpnpanel/stunnel}/tunnels"
STUNNEL_ACTIVE_CONFIG="${STUNNEL_CONFIG:-/etc/stunnel/stunnel.conf}"
STUNNEL_CERTS_DIR="${CERT_DIR:-/etc/sshvpnpanel/certs}"

# Initialize Stunnel management
init_stunnel_management() {
    mkdir -p "${STUNNEL_TUNNELS_DIR}" 2>/dev/null
    mkdir -p "${STUNNEL_CERTS_DIR}" 2>/dev/null
    chmod 700 "${STUNNEL_CERTS_DIR}" 2>/dev/null
    mkdir -p "$(dirname "${STUNNEL_ACTIVE_CONFIG}")" 2>/dev/null
}

# Get tunnel config file path
tunnel_config_file() {
    local name="$1"
    echo "${STUNNEL_TUNNELS_DIR}/${name}.conf"
}

# Check if tunnel exists
tunnel_exists() {
    local name="$1"
    [[ -f "$(tunnel_config_file "${name}")" ]]
}

# =============================================================================
# STUNNEL SERVICE MANAGEMENT
# =============================================================================

stunnel_service_status() {
    service_status "${STUNNEL_SERVICE:-stunnel4}"
}

stunnel_start() {
    require_root || return 1
    print_info "Starting Stunnel service..."

    if [[ "$(stunnel_service_status)" == "running" ]]; then
        print_warning "Stunnel is already running"
        return 0
    fi

    # Generate configuration before starting
    generate_stunnel_config || return 1

    if service_start "${STUNNEL_SERVICE:-stunnel4}"; then
        print_success "Stunnel started successfully"
        log_audit "stunnel_start" "service=${STUNNEL_SERVICE:-stunnel4}"
    else
        print_error "Failed to start Stunnel"
        return 1
    fi
}

stunnel_stop() {
    require_root || return 1
    print_info "Stopping Stunnel service..."

    if service_stop "${STUNNEL_SERVICE:-stunnel4}"; then
        print_success "Stunnel stopped"
        log_audit "stunnel_stop" "service=${STUNNEL_SERVICE:-stunnel4}"
    else
        print_error "Failed to stop Stunnel"
        return 1
    fi
}

stunnel_restart() {
    require_root || return 1
    print_info "Restarting Stunnel service..."

    generate_stunnel_config || return 1

    if service_restart "${STUNNEL_SERVICE:-stunnel4}"; then
        print_success "Stunnel restarted"
        log_audit "stunnel_restart" "service=${STUNNEL_SERVICE:-stunnel4}"
    else
        print_error "Failed to restart Stunnel"
        return 1
    fi
}

stunnel_reload() {
    require_root || return 1
    print_info "Reloading Stunnel configuration..."

    generate_stunnel_config || return 1

    local pid
    pid="$(cat "${STUNNEL_PID_FILE:-/var/run/stunnel4/stunnel4.pid}" 2>/dev/null)"
    if [[ -n "${pid}" ]] && kill -0 "${pid}" 2>/dev/null; then
        kill -HUP "${pid}"
        print_success "Stunnel configuration reloaded"
        log_audit "stunnel_reload" ""
    else
        stunnel_restart
    fi
}

# =============================================================================
# STUNNEL CONFIGURATION GENERATION
# =============================================================================

generate_stunnel_config() {
    require_root || return 1
    print_info "Generating Stunnel configuration..."

    local config_dir
    config_dir="$(dirname "${STUNNEL_ACTIVE_CONFIG}")"
    mkdir -p "${config_dir}" 2>/dev/null

    # Create directories for stunnel
    mkdir -p "$(dirname "${STUNNEL_PID_FILE:-/var/run/stunnel4/stunnel4.pid}")" 2>/dev/null
    mkdir -p "$(dirname "${STUNNEL_LOG_FILE:-/var/log/stunnel4/stunnel4.log}")" 2>/dev/null

    # Write global configuration
    local tmp_config="${STUNNEL_ACTIVE_CONFIG}.tmp.$$"
    cat > "${tmp_config}" << EOF
; =============================================================================
; Stunnel Configuration - Generated by SSH VPN Panel
; Generated: $(get_timestamp)
; =============================================================================

; Global settings
setuid = stunnel4
setgid = stunnel4

; PID file
pid = ${STUNNEL_PID_FILE:-/var/run/stunnel4/stunnel4.pid}

; Log file
output = ${STUNNEL_LOG_FILE:-/var/log/stunnel4/stunnel4.log}

; Log level (0-7)
debug = 5

; Socket options for better performance
socket = l:TCP_NODELAY=1
socket = r:TCP_NODELAY=1

EOF

    # Append each tunnel configuration
    if [[ -d "${STUNNEL_TUNNELS_DIR}" ]]; then
        local tunnel_count=0
        for tunnel_file in "${STUNNEL_TUNNELS_DIR}"/*.conf; do
            [[ -f "${tunnel_file}" ]] || continue
            local tunnel_name
            tunnel_name="$(basename "${tunnel_file}" .conf)"
            local enabled
            enabled="$(config_get "${tunnel_file}" "ENABLED" "yes")"

            if [[ "${enabled}" == "yes" ]]; then
                echo "; --- Tunnel: ${tunnel_name} ---" >> "${tmp_config}"
                _generate_tunnel_section "${tunnel_file}" >> "${tmp_config}"
                echo >> "${tmp_config}"
                (( tunnel_count++ ))
            fi
        done
        print_info "Generated config with ${tunnel_count} active tunnels"
    fi

    # Atomically replace the config
    mv "${tmp_config}" "${STUNNEL_ACTIVE_CONFIG}"
    chmod 600 "${STUNNEL_ACTIVE_CONFIG}"

    print_success "Stunnel configuration generated: ${STUNNEL_ACTIVE_CONFIG}"
    return 0
}

# Generate a single tunnel's configuration section
_generate_tunnel_section() {
    local tunnel_file="$1"

    local name
    name="$(config_get "${tunnel_file}" "NAME")"
    local accept
    accept="$(config_get "${tunnel_file}" "ACCEPT")"
    local connect
    connect="$(config_get "${tunnel_file}" "CONNECT")"
    local cert
    cert="$(config_get "${tunnel_file}" "CERT")"
    local key
    key="$(config_get "${tunnel_file}" "KEY")"
    local tls_version
    tls_version="$(config_get "${tunnel_file}" "TLS_VERSION" "TLSv1.3")"
    local ca_file
    ca_file="$(config_get "${tunnel_file}" "CA_FILE" "")"
    local verify
    verify="$(config_get "${tunnel_file}" "VERIFY" "0")"
    local protocol
    protocol="$(config_get "${tunnel_file}" "PROTOCOL" "")"
    local sni_names
    sni_names="$(config_get "${tunnel_file}" "SNI_NAMES" "")"
    local timeout_close
    timeout_close="$(config_get "${tunnel_file}" "TIMEOUT_CLOSE" "0")"

    echo "[${name}]"
    echo "accept  = ${accept}"
    echo "connect = ${connect}"

    if [[ -n "${cert}" && -f "${cert}" ]]; then
        echo "cert    = ${cert}"
    fi
    if [[ -n "${key}" && -f "${key}" ]]; then
        echo "key     = ${key}"
    fi
    if [[ -n "${ca_file}" && -f "${ca_file}" ]]; then
        echo "CAfile  = ${ca_file}"
        echo "verify  = ${verify}"
    fi
    if [[ -n "${tls_version}" ]]; then
        echo "sslVersion = ${tls_version}"
    fi
    if [[ -n "${protocol}" ]]; then
        echo "protocol = ${protocol}"
    fi
    if [[ -n "${sni_names}" ]]; then
        echo "sniNames = ${sni_names}"
    fi
    echo "TIMEOUTclose = ${timeout_close}"
}

# =============================================================================
# TUNNEL MANAGEMENT
# =============================================================================

add_tunnel() {
    local name="$1"
    local accept_addr="$2"     # Format: [host:]port
    local connect_addr="$3"    # Format: host:port
    local cert_file="${4:-}"
    local key_file="${5:-}"
    local tls_version="${6:-TLSv1.3}"

    require_root || return 1

    # Validate name
    if [[ ! "${name}" =~ ^[a-zA-Z][a-zA-Z0-9_-]+$ ]]; then
        print_error "Invalid tunnel name. Use letters, numbers, dash, underscore."
        return 1
    fi

    if tunnel_exists "${name}"; then
        print_error "Tunnel '${name}' already exists"
        return 1
    fi

    # If no cert provided, generate a self-signed one
    if [[ -z "${cert_file}" ]] || [[ ! -f "${cert_file}" ]]; then
        print_info "No certificate specified. Generating self-signed certificate..."
        local generated_cert="${STUNNEL_CERTS_DIR}/${name}.crt"
        local generated_key="${STUNNEL_CERTS_DIR}/${name}.key"
        generate_self_signed_cert "${name}" "${generated_cert}" "${generated_key}" || return 1
        cert_file="${generated_cert}"
        key_file="${generated_key}"
    fi

    # Create tunnel configuration
    mkdir -p "${STUNNEL_TUNNELS_DIR}" 2>/dev/null
    cat > "$(tunnel_config_file "${name}")" << EOF
# Stunnel Tunnel Configuration
NAME=${name}
ACCEPT=${accept_addr}
CONNECT=${connect_addr}
CERT=${cert_file}
KEY=${key_file}
TLS_VERSION=${tls_version}
ENABLED=yes
PROTOCOL=
SNI_NAMES=
CA_FILE=
VERIFY=0
TIMEOUT_CLOSE=0
CREATED=$(get_timestamp)
BYTES_IN=0
BYTES_OUT=0
CONNECTIONS=0
NOTES=
EOF
    chmod 600 "$(tunnel_config_file "${name}")"

    print_success "Tunnel '${name}' created"
    print_info "  Accept:  ${accept_addr}"
    print_info "  Connect: ${connect_addr}"
    print_info "  TLS:     ${tls_version}"
    print_info "  Cert:    ${cert_file}"

    log_audit "stunnel_add" "name=${name},accept=${accept_addr},connect=${connect_addr}"
    return 0
}

remove_tunnel() {
    local name="$1"

    require_root || return 1

    if ! tunnel_exists "${name}"; then
        print_error "Tunnel '${name}' not found"
        return 1
    fi

    confirm "Remove tunnel '${name}'?" "no" || return 0

    rm -f "$(tunnel_config_file "${name}")"
    print_success "Tunnel '${name}' removed"

    # Regenerate and reload config
    generate_stunnel_config && stunnel_reload 2>/dev/null || true

    log_audit "stunnel_remove" "name=${name}"
}

enable_tunnel() {
    local name="$1"

    require_root || return 1

    if ! tunnel_exists "${name}"; then
        print_error "Tunnel '${name}' not found"
        return 1
    fi

    config_set "$(tunnel_config_file "${name}")" "ENABLED" "yes"
    generate_stunnel_config && stunnel_reload 2>/dev/null || true
    print_success "Tunnel '${name}' enabled"
    log_audit "stunnel_enable" "name=${name}"
}

disable_tunnel() {
    local name="$1"

    require_root || return 1

    if ! tunnel_exists "${name}"; then
        print_error "Tunnel '${name}' not found"
        return 1
    fi

    config_set "$(tunnel_config_file "${name}")" "ENABLED" "no"
    generate_stunnel_config && stunnel_reload 2>/dev/null || true
    print_success "Tunnel '${name}' disabled"
    log_audit "stunnel_disable" "name=${name}"
}

list_tunnels() {
    clear_screen
    print_header "Stunnel Tunnels"

    local service_status
    service_status="$(stunnel_service_status)"
    echo -e "  Service Status: $(print_status "${service_status}")\n"

    if [[ ! -d "${STUNNEL_TUNNELS_DIR}" ]] || \
       [[ -z "$(ls -A "${STUNNEL_TUNNELS_DIR}" 2>/dev/null)" ]]; then
        print_info "No tunnels configured"
        return
    fi

    print_table_header "Name" "Accept" "Connect" "TLS" "Status"

    for tunnel_file in "${STUNNEL_TUNNELS_DIR}"/*.conf; do
        [[ -f "${tunnel_file}" ]] || continue
        local name
        name="$(config_get "${tunnel_file}" "NAME")"
        local accept
        accept="$(config_get "${tunnel_file}" "ACCEPT")"
        local connect
        connect="$(config_get "${tunnel_file}" "CONNECT")"
        local tls
        tls="$(config_get "${tunnel_file}" "TLS_VERSION" "TLSv1.3")"
        local enabled
        enabled="$(config_get "${tunnel_file}" "ENABLED" "yes")"

        local status_color="${C_SUCCESS}"
        [[ "${enabled}" != "yes" ]] && status_color="${C_DIM}"

        printf "  ${C_BOLD}%-16s${C_RESET} %-14s %-20s %-10s ${status_color}%s${C_RESET}\n" \
            "${name}" "${accept}" "${connect}" "${tls}" \
            "$([ "${enabled}" == "yes" ] && echo "enabled" || echo "disabled")"
    done
}

show_tunnel_detail() {
    local name="$1"

    if ! tunnel_exists "${name}"; then
        print_error "Tunnel '${name}' not found"
        return 1
    fi

    local tunnel_file
    tunnel_file="$(tunnel_config_file "${name}")"

    clear_screen
    print_header "Tunnel Detail: ${name}"

    local fields=(
        "Name:$(config_get "${tunnel_file}" "NAME")"
        "Accept:$(config_get "${tunnel_file}" "ACCEPT")"
        "Connect:$(config_get "${tunnel_file}" "CONNECT")"
        "Certificate:$(config_get "${tunnel_file}" "CERT")"
        "Private Key:$(config_get "${tunnel_file}" "KEY")"
        "TLS Version:$(config_get "${tunnel_file}" "TLS_VERSION")"
        "Protocol:$(config_get "${tunnel_file}" "PROTOCOL" "(default)")"
        "SNI Names:$(config_get "${tunnel_file}" "SNI_NAMES" "(none)")"
        "Enabled:$(config_get "${tunnel_file}" "ENABLED")"
        "Created:$(config_get "${tunnel_file}" "CREATED")"
    )

    for field in "${fields[@]}"; do
        local key="${field%%:*}"
        local val="${field#*:}"
        printf "  ${C_BOLD}%-20s${C_RESET} %s\n" "${key}:" "${val}"
    done

    # Check certificate validity
    local cert
    cert="$(config_get "${tunnel_file}" "CERT")"
    if [[ -f "${cert}" ]]; then
        echo -e "\n${C_BOLD}Certificate Status${C_RESET}"
        print_separator 40
        local expiry
        expiry="$(openssl x509 -enddate -noout -in "${cert}" 2>/dev/null | cut -d= -f2)"
        local subject
        subject="$(openssl x509 -subject -noout -in "${cert}" 2>/dev/null | sed 's/subject=//')"
        printf "  ${C_BOLD}%-20s${C_RESET} %s\n" "Subject:" "${subject}"
        printf "  ${C_BOLD}%-20s${C_RESET} %s\n" "Expires:" "${expiry}"
    fi
}

# =============================================================================
# CERTIFICATE MANAGEMENT
# =============================================================================

generate_self_signed_cert() {
    local common_name="${1:-stunnel}"
    local cert_file="${2:-${STUNNEL_CERTS_DIR}/${common_name}.crt}"
    local key_file="${3:-${STUNNEL_CERTS_DIR}/${common_name}.key}"
    local days="${4:-${DEFAULT_CERT_DAYS:-365}}"

    require_root || return 1

    if ! command_exists openssl; then
        print_error "openssl is required to generate certificates"
        return 1
    fi

    mkdir -p "${STUNNEL_CERTS_DIR}" 2>/dev/null
    chmod 700 "${STUNNEL_CERTS_DIR}" 2>/dev/null

    print_info "Generating self-signed certificate for '${common_name}'..."

    if openssl req -x509 -newkey rsa:4096 -keyout "${key_file}" \
        -out "${cert_file}" -days "${days}" -nodes \
        -subj "/CN=${common_name}/O=SSH VPN Panel/C=US" 2>/dev/null; then

        chmod 600 "${key_file}"
        chmod 644 "${cert_file}"

        print_success "Certificate generated:"
        print_info "  Certificate: ${cert_file}"
        print_info "  Private Key: ${key_file}"
        print_info "  Valid for:   ${days} days"

        # Show certificate details
        local expiry
        expiry="$(openssl x509 -enddate -noout -in "${cert_file}" 2>/dev/null | cut -d= -f2)"
        print_info "  Expires:     ${expiry}"

        log_audit "cert_generate" "cn=${common_name},file=${cert_file}"
        return 0
    else
        print_error "Failed to generate certificate"
        return 1
    fi
}

generate_ca() {
    local ca_name="${1:-sshvpnpanel-ca}"
    local ca_dir="${STUNNEL_CERTS_DIR}/ca"

    require_root || return 1

    if ! command_exists openssl; then
        print_error "openssl is required"
        return 1
    fi

    mkdir -p "${ca_dir}" 2>/dev/null

    print_info "Generating CA certificate..."

    # Generate CA key
    openssl genrsa -out "${ca_dir}/ca.key" 4096 2>/dev/null || return 1
    chmod 600 "${ca_dir}/ca.key"

    # Generate CA certificate
    openssl req -x509 -new -nodes -key "${ca_dir}/ca.key" \
        -sha256 -days 3650 -out "${ca_dir}/ca.crt" \
        -subj "/CN=${ca_name}/O=SSH VPN Panel CA/C=US" 2>/dev/null || return 1
    chmod 644 "${ca_dir}/ca.crt"

    print_success "CA certificate generated:"
    print_info "  CA Key:  ${ca_dir}/ca.key"
    print_info "  CA Cert: ${ca_dir}/ca.crt"

    log_audit "ca_generate" "name=${ca_name}"
    return 0
}

sign_certificate_with_ca() {
    local domain="$1"
    local ca_dir="${STUNNEL_CERTS_DIR}/ca"
    local cert_dir="${STUNNEL_CERTS_DIR}"

    require_root || return 1

    if [[ ! -f "${ca_dir}/ca.key" ]]; then
        print_error "CA not found. Generate CA first."
        return 1
    fi

    print_info "Signing certificate for domain: ${domain}..."

    # Generate server key
    openssl genrsa -out "${cert_dir}/${domain}.key" 4096 2>/dev/null || return 1
    chmod 600 "${cert_dir}/${domain}.key"

    # Generate CSR
    openssl req -new -key "${cert_dir}/${domain}.key" \
        -out "${cert_dir}/${domain}.csr" \
        -subj "/CN=${domain}/O=SSH VPN Panel/C=US" 2>/dev/null || return 1

    # Sign with CA
    openssl x509 -req -in "${cert_dir}/${domain}.csr" \
        -CA "${ca_dir}/ca.crt" -CAkey "${ca_dir}/ca.key" \
        -CAcreateserial -out "${cert_dir}/${domain}.crt" \
        -days "${DEFAULT_CERT_DAYS:-365}" -sha256 2>/dev/null || return 1

    chmod 644 "${cert_dir}/${domain}.crt"
    rm -f "${cert_dir}/${domain}.csr"

    print_success "Certificate signed for ${domain}"
    print_info "  Certificate: ${cert_dir}/${domain}.crt"
    print_info "  Private Key: ${cert_dir}/${domain}.key"

    log_audit "cert_sign" "domain=${domain}"
    return 0
}

list_certificates() {
    clear_screen
    print_header "SSL/TLS Certificates"

    if [[ ! -d "${STUNNEL_CERTS_DIR}" ]]; then
        print_info "No certificates directory found"
        return
    fi

    local certs=()
    while IFS= read -r -d '' cert_file; do
        certs+=("${cert_file}")
    done < <(find "${STUNNEL_CERTS_DIR}" -name "*.crt" -not -path "*/ca/*" -print0 2>/dev/null)

    if [[ ${#certs[@]} -eq 0 ]]; then
        print_info "No certificates found"
        return
    fi

    print_table_header "Certificate" "Subject" "Expires" "Days Left"

    for cert_file in "${certs[@]}"; do
        local cert_name
        cert_name="$(basename "${cert_file}" .crt)"
        local subject
        subject="$(openssl x509 -subject -noout -in "${cert_file}" 2>/dev/null | sed 's/.*CN=//' | cut -d'/' -f1)"
        local expiry_str
        expiry_str="$(openssl x509 -enddate -noout -in "${cert_file}" 2>/dev/null | cut -d= -f2)"
        local expiry_date
        expiry_date="$(date -d "${expiry_str}" '+%Y-%m-%d' 2>/dev/null || echo "${expiry_str}")"
        local days_left
        days_left="$(days_until_expiry "${expiry_date}")"

        local days_color="${C_SUCCESS}"
        if [[ "${days_left}" =~ ^-?[0-9]+$ ]]; then
            [[ "${days_left}" -lt 30 ]] && days_color="${C_WARNING}"
            [[ "${days_left}" -lt 0 ]] && days_color="${C_ERROR}"
        fi

        printf "  ${C_BOLD}%-20s${C_RESET} %-24s %-14s ${days_color}%s${C_RESET}\n" \
            "${cert_name}" "${subject}" "${expiry_date}" "${days_left} days"
    done
}

renew_certificate() {
    local cert_name="$1"
    local cert_file="${STUNNEL_CERTS_DIR}/${cert_name}.crt"
    local key_file="${STUNNEL_CERTS_DIR}/${cert_name}.key"

    require_root || return 1

    if [[ ! -f "${cert_file}" ]]; then
        print_error "Certificate '${cert_name}' not found"
        return 1
    fi

    print_info "Renewing certificate: ${cert_name}"

    # Backup existing cert
    local backup_dir="${BACKUP_DIR:-/var/backups/sshvpnpanel}/certs"
    mkdir -p "${backup_dir}" 2>/dev/null
    cp "${cert_file}" "${backup_dir}/${cert_name}_$(date +%Y%m%d).crt.bak" 2>/dev/null

    # Re-generate self-signed certificate
    generate_self_signed_cert "${cert_name}" "${cert_file}" "${key_file}" \
        "${DEFAULT_CERT_DAYS:-365}" || return 1

    # Reload stunnel if running
    if [[ "$(stunnel_service_status)" == "running" ]]; then
        stunnel_reload
    fi

    log_audit "cert_renew" "name=${cert_name}"
}

check_expiring_certs() {
    local threshold="${CERT_RENEW_DAYS:-30}"
    print_info "Checking for certificates expiring within ${threshold} days..."

    local found=0
    if [[ -d "${STUNNEL_CERTS_DIR}" ]]; then
        while IFS= read -r -d '' cert_file; do
            local cert_name
            cert_name="$(basename "${cert_file}" .crt)"
            local expiry_str
            expiry_str="$(openssl x509 -enddate -noout -in "${cert_file}" 2>/dev/null | cut -d= -f2)"
            local expiry_date
            expiry_date="$(date -d "${expiry_str}" '+%Y-%m-%d' 2>/dev/null || echo "")"
            if [[ -z "${expiry_date}" ]]; then continue; fi

            local days_left
            days_left="$(days_until_expiry "${expiry_date}")"

            if [[ "${days_left}" =~ ^-?[0-9]+$ ]] && [[ "${days_left}" -lt "${threshold}" ]]; then
                print_warning "Certificate '${cert_name}' expires in ${days_left} days (${expiry_date})"
                (( found++ ))
            fi
        done < <(find "${STUNNEL_CERTS_DIR}" -name "*.crt" -print0 2>/dev/null)
    fi

    if [[ "${found}" -eq 0 ]]; then
        print_success "No certificates expiring within ${threshold} days"
    else
        print_warning "Found ${found} certificate(s) requiring attention"
    fi
}

# =============================================================================
# AUTO-RESTART WATCHDOG
# =============================================================================

stunnel_watchdog_start() {
    require_root || return 1

    if [[ "${STUNNEL_AUTO_RESTART:-yes}" != "yes" ]]; then
        print_info "Auto-restart is disabled in configuration"
        return 0
    fi

    local watchdog_script="/etc/sshvpnpanel/stunnel_watchdog.sh"
    local interval="${STUNNEL_CHECK_INTERVAL:-60}"

    cat > "${watchdog_script}" << 'WATCHDOG_EOF'
#!/usr/bin/env bash
# Stunnel watchdog - auto-restart on failure
STUNNEL_SERVICE="${STUNNEL_SERVICE:-stunnel4}"
LOG_FILE="${STUNNEL_LOG_FILE:-/var/log/stunnel4/stunnel4.log}"

check_and_restart() {
    if ! systemctl is-active --quiet "${STUNNEL_SERVICE}" 2>/dev/null; then
        echo "$(date '+%Y-%m-%d %H:%M:%S') [WATCHDOG] Stunnel not running, restarting..." >> "${LOG_FILE}"
        systemctl start "${STUNNEL_SERVICE}" 2>/dev/null
        echo "$(date '+%Y-%m-%d %H:%M:%S') [WATCHDOG] Restart attempted" >> "${LOG_FILE}"
    fi
}

while true; do
    check_and_restart
    sleep "${STUNNEL_CHECK_INTERVAL:-60}"
done
WATCHDOG_EOF
    chmod +x "${watchdog_script}"

    # Create systemd service for watchdog if available
    if [[ "$(get_service_manager)" == "systemd" ]]; then
        cat > "/etc/systemd/system/sshvpnpanel-stunnel-watchdog.service" << EOF
[Unit]
Description=SSH VPN Panel Stunnel Watchdog
After=network.target

[Service]
Type=simple
ExecStart=${watchdog_script}
Restart=always
RestartSec=10

[Install]
WantedBy=multi-user.target
EOF
        systemctl daemon-reload 2>/dev/null
        service_enable "sshvpnpanel-stunnel-watchdog" 2>/dev/null
        service_start "sshvpnpanel-stunnel-watchdog" 2>/dev/null
        print_success "Stunnel watchdog service started"
    else
        # Start as background process
        nohup bash "${watchdog_script}" &>/dev/null &
        print_success "Stunnel watchdog started (PID: $!)"
    fi

    log_audit "stunnel_watchdog_start" "interval=${interval}"
}

stunnel_watchdog_stop() {
    require_root || return 1

    if [[ "$(get_service_manager)" == "systemd" ]]; then
        service_stop "sshvpnpanel-stunnel-watchdog" 2>/dev/null || true
        print_success "Stunnel watchdog stopped"
    else
        pkill -f "stunnel_watchdog.sh" 2>/dev/null || true
        print_success "Stunnel watchdog stopped"
    fi
    log_audit "stunnel_watchdog_stop" ""
}

# =============================================================================
# TRAFFIC MONITORING
# =============================================================================

show_stunnel_stats() {
    clear_screen
    print_header "Stunnel Traffic Statistics"

    local log_file="${STUNNEL_LOG_FILE:-/var/log/stunnel4/stunnel4.log}"

    if [[ ! -f "${log_file}" ]]; then
        print_info "No Stunnel log file found at ${log_file}"
        return
    fi

    # Count connections from log
    local total_connections
    total_connections="$(grep -c "Connection from" "${log_file}" 2>/dev/null || echo "0")"
    local today_connections
    today_connections="$(grep "$(date '+%Y.%m.%d')" "${log_file}" 2>/dev/null | \
        grep -c "Connection from" || echo "0")"
    local error_count
    error_count="$(grep -c "Error\|error" "${log_file}" 2>/dev/null || echo "0")"

    echo -e "\n${C_BOLD}Summary Statistics${C_RESET}"
    print_separator 40
    printf "  %-30s %s\n" "Total connections:" "${total_connections}"
    printf "  %-30s %s\n" "Today's connections:" "${today_connections}"
    printf "  %-30s %s\n" "Error count:" "${error_count}"

    echo -e "\n${C_BOLD}Recent Log Entries${C_RESET}"
    print_separator 40
    tail -20 "${log_file}" | while IFS= read -r line; do
        local color="${C_DIM}"
        [[ "${line}" =~ [Ee]rror|WARN ]] && color="${C_WARNING}"
        [[ "${line}" =~ [Ee]mergency|EMERG ]] && color="${C_ERROR}"
        echo -e "  ${color}${line}${C_RESET}"
    done
}

# =============================================================================
# STUNNEL MANAGEMENT MENU
# =============================================================================

stunnel_management_menu() {
    while true; do
        clear_screen
        print_header "Stunnel Management"

        local svc_status
        svc_status="$(stunnel_service_status)"
        echo -e "  Service: $(print_status "${svc_status}")\n"

        echo -e "${C_BOLD}Service Control:${C_RESET}"
        echo "  1. Start Stunnel"
        echo "  2. Stop Stunnel"
        echo "  3. Restart Stunnel"
        echo "  4. Reload Configuration"
        echo
        echo -e "${C_BOLD}Tunnel Management:${C_RESET}"
        echo "  5. Add Tunnel"
        echo "  6. Remove Tunnel"
        echo "  7. Enable/Disable Tunnel"
        echo "  8. List Tunnels"
        echo "  9. Tunnel Details"
        echo
        echo -e "${C_BOLD}Certificate Management:${C_RESET}"
        echo " 10. Generate Self-Signed Certificate"
        echo " 11. Generate CA Certificate"
        echo " 12. Sign Certificate with CA"
        echo " 13. List Certificates"
        echo " 14. Renew Certificate"
        echo " 15. Check Expiring Certificates"
        echo
        echo -e "${C_BOLD}Monitoring:${C_RESET}"
        echo " 16. View Traffic Stats"
        echo " 17. Start/Stop Watchdog"
        echo "  0. Back to Main Menu"
        echo

        local choice
        choice="$(read_int "Select option" 0 17)"

        case "${choice}" in
            1) stunnel_start; read -rp $'\nPress Enter to continue...' ;;
            2) stunnel_stop; read -rp $'\nPress Enter to continue...' ;;
            3) stunnel_restart; read -rp $'\nPress Enter to continue...' ;;
            4) stunnel_reload; read -rp $'\nPress Enter to continue...' ;;
            5) _menu_add_tunnel ;;
            6) _menu_remove_tunnel ;;
            7) _menu_toggle_tunnel ;;
            8) list_tunnels; read -rp $'\nPress Enter to continue...' ;;
            9) _menu_tunnel_detail ;;
            10) _menu_gen_self_signed ;;
            11) _menu_gen_ca ;;
            12) _menu_sign_cert ;;
            13) list_certificates; read -rp $'\nPress Enter to continue...' ;;
            14) _menu_renew_cert ;;
            15) check_expiring_certs; read -rp $'\nPress Enter to continue...' ;;
            16) show_stunnel_stats; read -rp $'\nPress Enter to continue...' ;;
            17) _menu_watchdog ;;
            0) return 0 ;;
        esac
    done
}

_menu_add_tunnel() {
    clear_screen
    print_header "Add Stunnel Tunnel"

    local name
    read_input "Tunnel name (e.g., ssh-ssl)" "" name
    [[ -z "${name}" ]] && return

    local accept
    read_input "Accept address (e.g., 0.0.0.0:443)" "0.0.0.0:443" accept
    accept="${accept:-0.0.0.0:443}"

    local connect
    read_input "Connect to (e.g., 127.0.0.1:22)" "127.0.0.1:22" connect
    connect="${connect:-127.0.0.1:22}"

    echo "TLS versions: 1.TLSv1.2  2.TLSv1.3  3.TLSv1.2,TLSv1.3"
    local tls_choice
    tls_choice="$(read_int "TLS version" 1 3 "2")"
    local tls_versions=("TLSv1.2" "TLSv1.3" "TLSv1.2,TLSv1.3")
    local tls="${tls_versions[$((tls_choice-1))]}"

    local cert_path
    read_input "Certificate file path (empty to auto-generate)" "" cert_path

    echo
    add_tunnel "${name}" "${accept}" "${connect}" "${cert_path}" "" "${tls}"
    read -rp $'\nPress Enter to continue...'
}

_menu_remove_tunnel() {
    list_tunnels
    echo
    local name
    read_input "Tunnel name to remove (or 'cancel')" "" name
    [[ "${name}" == "cancel" || -z "${name}" ]] && return
    remove_tunnel "${name}"
    read -rp $'\nPress Enter to continue...'
}

_menu_toggle_tunnel() {
    list_tunnels
    echo
    local name
    read_input "Tunnel name" "" name
    [[ -z "${name}" ]] && return

    if ! tunnel_exists "${name}"; then
        print_error "Tunnel '${name}' not found"
    else
        local enabled
        enabled="$(config_get "$(tunnel_config_file "${name}")" "ENABLED" "yes")"
        if [[ "${enabled}" == "yes" ]]; then
            disable_tunnel "${name}"
        else
            enable_tunnel "${name}"
        fi
    fi
    read -rp $'\nPress Enter to continue...'
}

_menu_tunnel_detail() {
    local name
    read_input "Tunnel name" "" name
    [[ -z "${name}" ]] && return
    show_tunnel_detail "${name}"
    read -rp $'\nPress Enter to continue...'
}

_menu_gen_self_signed() {
    clear_screen
    print_header "Generate Self-Signed Certificate"

    local cn
    read_input "Common Name (hostname or domain)" "stunnel" cn
    cn="${cn:-stunnel}"

    local cert_file="${STUNNEL_CERTS_DIR}/${cn}.crt"
    local key_file="${STUNNEL_CERTS_DIR}/${cn}.key"

    if [[ -f "${cert_file}" ]]; then
        confirm "Certificate '${cn}' already exists. Overwrite?" "no" || return
    fi

    local days
    days="$(read_int "Validity in days" 1 3650 "${DEFAULT_CERT_DAYS:-365}")"

    generate_self_signed_cert "${cn}" "${cert_file}" "${key_file}" "${days}"
    read -rp $'\nPress Enter to continue...'
}

_menu_gen_ca() {
    clear_screen
    print_header "Generate CA Certificate"
    local ca_name
    read_input "CA name" "sshvpnpanel-ca" ca_name
    ca_name="${ca_name:-sshvpnpanel-ca}"
    generate_ca "${ca_name}"
    read -rp $'\nPress Enter to continue...'
}

_menu_sign_cert() {
    clear_screen
    print_header "Sign Certificate with CA"
    local domain
    read_input "Domain name" "" domain
    [[ -z "${domain}" ]] && return
    sign_certificate_with_ca "${domain}"
    read -rp $'\nPress Enter to continue...'
}

_menu_renew_cert() {
    list_certificates
    echo
    local name
    read_input "Certificate name to renew (without .crt)" "" name
    [[ -z "${name}" ]] && return
    renew_certificate "${name}"
    read -rp $'\nPress Enter to continue...'
}

_menu_watchdog() {
    echo
    echo "  1. Start Watchdog"
    echo "  2. Stop Watchdog"
    local choice
    choice="$(read_int "Select" 1 2)"
    if [[ "${choice}" -eq 1 ]]; then
        stunnel_watchdog_start
    else
        stunnel_watchdog_stop
    fi
    read -rp $'\nPress Enter to continue...'
}
